users:
  - name: "norbert"
    group: "devops"
    shell: "/bin/bash"
    authorized: 
      - n.pub
  - name: "konrad"
    shell: "/bin/sh"
    group: "logs"
    authorized: 
      - k.pub
  - name: "jenkins"
    shell: "/bin/bash"
    group: "devops"
    authorized: 
      - jenkins.pub

sudoers_group:
  - group_name: "devops"


packages:
    - package: openjdk-11-jdk
    - package: python3-pip
    - package: packer
    - package: ansible

packer_key:
  - key: https://apt.releases.hashicorp.com/gpg
    state: present

packer_repository: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"