users:
  - name: "norbert"
    group: "devops"
    shell: "/bin/bash"
    authorized: 
      - n.pub
  - name: "konrad"
    shell: "/bin/sh"
    group: "logs"
    authorized: 
      - k.pub

sudoers_group:
  - group_name: "devops"


packages:
  java: 
      java: openjdk-11-jdk
      state: present