users:
  - name: "norbert"
    shell: "/bin/bash"
    group: "devops"
    authorized: 
      - n.pub
  - name: "konrad"
    shell: "/bin/sh"
    group: "logs"
    authorized: 
      - k.pub
  - name: "jenkins"
    shell: "/bin/bash"
    group: "devops"
    authorized: 
      - jenkins.pub

sudoers_group:
  - group_name: "devops"

packages:
    - package: openjdk-11-jdk


key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
repository_entry: "deb https://pkg.jenkins.io/debian-stable binary/"
