- name: Add Packer apt-key
  apt_key:
    url: "{{ item.key }}"
    state: "{{ item.state }}"
  with_items: "{{ packer_key }}"


- name: Add Packer APT repository
  shell: "{{ packer_repository }}"

- name: Install dependencis java 11 pip3 packer and ansible
  apt: 
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items: "{{ packages }}"



