- name: create group
  group:
    name: "{{ item.group }}"
    state: present
  with_items:
  - "{{ users }}"

- name: add users
  user:
    name: "{{ item.name}}"
    group: "{{ item.group }}"
    append: yes
    shell: "{{ item.shell }}"
  with_items:
  - "{{ users }}"


- name: Add public key to authorized_keys
  authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{ users }}"
    - authorized


- name: sudo without password for {{ item.group_name }} group
  copy:
    content: '%{{ item.group_name }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/{{item.group_name}}_nopasswd
    mode: 440
  with_items:
  - "{{ sudoers_group }}"