- hosts:
  - nginx_php
  roles:
    - update_hosts
    - add_user
    - hostname
    - nginx_php
    

- hosts:
  - jenkins
  roles:
    - update_hosts
    - add_user
    - hostname
    - install
    - jenkins
   


- hosts: jenkins_node
  roles:
    - update_hosts
    - add_user
    - hostname
    - install
    - jenkins_node

